### ISSUE TITLE
Docker Haproxy failure: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by guy-landry** [haproxytech/dataplaneapi#282]
Hi, I'm using the latest image from docker.

This is the error I'm getting from trying to run the dataplaneapi:

`/ # /usr/bin/dataplaneapi --port 5556 -b /usr/sbin/haproxy -c /etc/haproxy/haproxy.cfg  -d 5 -r "service 
haproxy reload" -s "service haproxy restart" -u dataplaneapi -t /tmp/haproxy
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x801358]

goroutine 1 [running]:
github.com/haproxytech/dataplaneapi/configuration.copyConfigurationToStorage(0x40003fef00)
	github.com/haproxytech/dataplaneapi/configuration/configuration_storage.go:532 +0x17f8
github.com/haproxytech/dataplaneapi/configuration.(*Configuration).Save(0x40003fef00)
	github.com/haproxytech/dataplaneapi/configuration/configuration.go:284 +0xc0
main.startServer(0x40003fef00)
	github.com/haproxytech/dataplaneapi/cmd/dataplaneapi/main.go:187 +0x1544
main.main()
	github.com/haproxytech/dataplaneapi/cmd/dataplaneapi/main.go:59 +0x38
/ # `

I tried older images with the same result.

**Comment by mjuraga** [comment]
Fixed with: https://github.com/haproxytech/dataplaneapi/commit/cf24d665987b5d678ba21a87ca6e2d435d85b8a1

**Comment by guy-landry** [comment]
Thanks. I'm still having the issue though. I suppose I should wait a bit for the change to take effect? Sorry I'm a beginner and not too familiar with the dev process.

**Comment by mjuraga** [comment]
Yes, we'll be issuing a release shortly and update the docker images, I'll let you know once that is done.
